---
abstract: 'A moose role ment to simplify writing of user level perl daemons.'
author:
  - 'Tore Andersson, C<< <tore.andersson at gmail.com> >>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-UserDaemon
no_index:
  directory:
    - inc
    - t
requires:
  English: 0
  Fcntl: 0
  File::Basename: 0
  File::HomeDir: 0
  File::Path: 0
  Moose::Role: 0
  POSIX: 0
  namespace::autoclean: 0
  perl: 5.14.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.05
