---
abstract: 'Simplify writing of user space daemons'
author:
  - 'Tore Andersson <tore.andersson@gmail.com>'
build_requires:
  Data::Dumper: '0'
  File::Temp: '0'
  Moose: '0'
  Readonly: '0'
  Test::More: '0'
  Test::Most: '0'
  Test::Output: '0'
  strict: '0'
  warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MooseX-Role-UserDaemon
requires:
  English: '0'
  Fcntl: '0'
  File::Basename: '0'
  File::HomeDir: '0'
  File::Path: '0'
  File::Spec: '0'
  Moose::Role: '0'
  POSIX: '0'
  autodie: '0'
  namespace::autoclean: '0'
  perl: '5.014'
version: '0.05'
